### PR TITLE
Solutions for Chapter 1

### PR DESCRIPTION
**Pull request by rahulbhargav**
### Solutions for Chapter 1

cc @vrom911 @chshersh

### CODE REVIEW

**Comment by vrom911** [comment]
Hey @rahulbhargav , I have noticed that you mentioned us in the PR, but already merged this one. Would you like us to review this pull request, or you think it is fine? Either way, we are happy to help 🙂

**Comment by rahulbhargav** [comment]
Hi @vrom911, 

First of all, Thank you for creating such an awesome tutorial. 

I opened another pull request https://github.com/kowainik/learn4haskell/pull/184 here. 

The reason for creating another PR in your repository is that I'm not able to build the project on my machine to run the test cases. I tried to fix it but it took me a lot of time and I couldn't fix. So, I wanted to raise a PR in your repo to see the result of the test execution in the pipeline which I think is not a good idea. I see that you already added few comments there and I'm learning from them and working on resolving them. Thanks a lot for spending your time in reviewing my PR. 

I'm running the project on Mac OS Catalina and I'm facing the below issue. Any help or suggestion would be of great help for me. Because, for my next PRs I would like to run test locally first and then push the code. 

```
➜ make test-chapter1
cabal test doctest-chapter1 --enable-tests --test-show-details=direct
Resolving dependencies...
Build profile: -w ghc-8.10.2 -O1
In order, the following will be built (use -v for more details):
 - learn4haskell-0.0.0.0 (test:doctest-chapter1) (configuration changed)
Configuring test suite 'doctest-chapter1' for learn4haskell-0.0.0.0..
Preprocessing test suite 'doctest-chapter1' for learn4haskell-0.0.0.0..
Building test suite 'doctest-chapter1' for learn4haskell-0.0.0.0..
Linking /Users/rahul/Documents/haskell/learn4haskell/dist-newstyle/build/x86_64-osx/ghc-8.10.2/learn4haskell-0.0.0.0/t/doctest-chapter1/build/doctest-chapter1/doctest-chapter1 ...
ld: archive has no table of contents file '/Users/rahul/.cabal/store/ghc-8.10.2/dctst-0.17-9818717f/lib/libHSdctst-0.17-9818717f.a' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`gcc' failed in phase `Linker'. (Exit code: 1)
make: *** [test-chapter1] Error 1
```

**Comment by vrom911** [comment]
I see! This makes sense, no worries 🙂 

That error looks odd 🤔 I am on MacOS as well, but I don't have this issue.. I have spent some time looking for how this issue could be resolved, but haven't found anything useful.

I am really sorry that you are experiencing this 😞 

Could you please share if you used the instruction in the README to install the compiler and build tool?

Also, could you check the versions that you are using:

```shell
ghc --version
cabal --version
```

**Comment by rahulbhargav** [comment]
@vrom911 I followed the instructions from the README file. But, I previously had stack and GHC v8.8.3 installed on my machine. I performed an version upgrade of `ghcup` (to 0.1.11) and I executed the commands provided in the README. Now, I can see that the ghc and cabal versions are as expected. 
```
➜ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.10.2

➜ cabal --version
cabal-install version 3.2.0.0
compiled using version 3.2.0.0 of the Cabal library
```

**Comment by vrom911** [comment]
Thanks for providing this information!

You can also try to make

```shell
make clean
make build
```

To clean up cache and build again.

Otherwise, it looks like a Cabal bug.
The best way would be to ask in their issue tracker, maybe they could advice what can we do with this one: https://github.com/haskell/cabal/issues
Sorry that you are experiencing this 😞

**Comment by rahulbhargav** [comment]
@vrom911 Thanks a lot for taking your time to look into this issue. I tried some more time to fix it but no luck. I tried setting up VSCode dev container, but I was still facing the same issue. I believe it has something to do with nix package manager, but I couldn't figure out the exact problem. 

I created another user account on my mac and did the setup. Now, I am able to build and test the project. 😊 
I raised a [PR](https://github.com/rahulbhargav/learn4haskell/pull/2) with my solutions for Chapter 2. Kindly review it. Thanks again 😊

**Pull request merged**
